PREFIX sv: <https://w3id.org/srcnet/services#>
SELECT ?record ?id ?type ?scope WHERE {
  ?record a sv:SiteCapsRecord ; sv:siteCapsId ?id ; sv:siteCapsType ?type ;
          sv:scope ?scope ; sv:isForceDisabled true .
}
